### ISSUE TITLE
CR1 Light Bulbs Out

### ISSUE THREAD

**Issue by timfoley** [ga-dc/campus#16]
Two light "bulbs" in the back row of Classroom 1 don't work. One buzzes and blinks, but doesn't stay on.

**Comment by ebirving** [comment]
Any ETA on a fix for this?

**Comment by amychoi** [comment]
Yes - I found out I have to figure out the light bulbs myself and go to
Home Depot because the build out contractor doesn't have the information,
so I will work on this being fixed by end of next week.

Sorry for the delay and thanks for checking in!

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by ebirving** [comment]
Awesome! Thanks, Amy!

**Comment by Campus-Commander** [comment]
@bmartinowich  @timfoley @ebirving @amychoi Lights bulb situation is still in progress. After attempts to remove them ourselves and asking members of Front Lines and full time staff for assistance were unsuccessful- we're reaching out to our facilities team to see if they are able to provide guidance.

**Comment by JonRojas** [comment]
I'm doing some research on these bulbslubs/fixtures

**Comment by bmartinowich** [comment]
@JonRojas Any update on research for bulbs? Let us know -- thanks!

**Comment by bmartinowich** [comment]
@amychoi @JonRojas I think we can close this issue, since the projectors have been replaced -- can one of you confirm?

**Comment by amychoi** [comment]
This is about the light bulbs in the classroom, not the projector light
bulb. We can't figure out how to open them... without breaking them...

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

On Wed, Feb 17, 2016 at 4:54 PM, Brian Martinowich <notifications@github.com
